FROM python:3.10-slim-buster

WORKDIR /app
COPY src ./src
COPY documentation ./documentation
COPY .env requirements.txt app.py ./

RUN python -m pip install -r requirements.txt

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
