openapi: 3.0.0
info:
  title: Dog Walking Service
  description: The API for the Dog Walking App project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/krakamod/Dog-Walking-Service/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /users:
    get:
      tags:
      - Users
      description: returns all users
      responses:
        "200":
          description: All the users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          description: the unique identifier for the user
          format: int32
        name:
          type: string
        email:
          type: string
      description: a single user
